import { mutationType } from 'nexus'

export const Mutation = mutationType({
  definition(t) {
    t.crud.createOneUser()
    t.crud.updateOneUser()
    t.crud.upsertOneUser()
    t.crud.deleteOneUser()
    t.crud.updateManyUser()
    t.crud.deleteManyUser()
    t.crud.createOnePost()
    t.crud.updateOnePost()
    t.crud.upsertOnePost()
    t.crud.deleteOnePost()
    t.crud.updateManyPost()
    t.crud.deleteManyPost()
    t.crud.createOneComment()
    t.crud.updateOneComment()
    t.crud.upsertOneComment()
    t.crud.deleteOneComment()
    t.crud.updateManyComment()
    t.crud.deleteManyComment()
    t.crud.createOneTag()
    t.crud.updateOneTag()
    t.crud.upsertOneTag()
    t.crud.deleteOneTag()
    t.crud.updateManyTag()
    t.crud.deleteManyTag()
    t.crud.createOneCategory()
    t.crud.updateOneCategory()
    t.crud.upsertOneCategory()
    t.crud.deleteOneCategory()
    t.crud.updateManyCategory()
    t.crud.deleteManyCategory()
  },
})
